services:
  - type: web
    name: calpal-backend
    env: node
    plan: free # or your desired plan
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables from your Render dashboard
      # Example:
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: your-db-name
      #     property: connectionString 